package `is`.xyz.mpv

import android.view.KeyEvent

val KeyMapping: Map<Int, String> = mapOf(
    KeyEvent.KEYCODE_SPACE to "SPACE",
    KeyEvent.KEYCODE_ENTER to "ENTER",
    KeyEvent.KEYCODE_TAB to "TAB",
    KeyEvent.KEYCODE_DEL to "BS",
    KeyEvent.KEYCODE_FORWARD_DEL to "DEL",
    KeyEvent.KEYCODE_INSERT to "INS",
    KeyEvent.KEYCODE_MOVE_HOME to "HOME",
    KeyEvent.KEYCODE_MOVE_END to "END",
    KeyEvent.KEYCODE_PAGE_UP to "PGUP",
    KeyEvent.KEYCODE_PAGE_DOWN to "PGDWN",
    KeyEvent.KEYCODE_ESCAPE to "ESC",
    KeyEvent.KEYCODE_SYSRQ to "PRINT",
    KeyEvent.KEYCODE_DPAD_RIGHT to "RIGHT",
    KeyEvent.KEYCODE_DPAD_LEFT to "LEFT",
    KeyEvent.KEYCODE_DPAD_DOWN to "DOWN",
    KeyEvent.KEYCODE_DPAD_UP to "UP",
    KeyEvent.KEYCODE_MEDIA_PLAY to "PLAYONLY",
    KeyEvent.KEYCODE_MEDIA_PAUSE to "PAUSEONLY",
    KeyEvent.KEYCODE_MEDIA_PLAY_PAUSE to "PLAYPAUSE",
    KeyEvent.KEYCODE_MEDIA_STOP to "STOP",
    KeyEvent.KEYCODE_MEDIA_FAST_FORWARD to "FORWARD",
    KeyEvent.KEYCODE_MEDIA_REWIND to "REWIND",
    KeyEvent.KEYCODE_MEDIA_NEXT to "NEXT",
    KeyEvent.KEYCODE_MEDIA_PREVIOUS to "PREV",
    KeyEvent.KEYCODE_MEDIA_RECORD to "RECORD",
    KeyEvent.KEYCODE_CHANNEL_UP to "CHANNEL_UP",
    KeyEvent.KEYCODE_CHANNEL_DOWN to "CHANNEL_DOWN",
    KeyEvent.KEYCODE_ZOOM_IN to "ZOOMIN",
    KeyEvent.KEYCODE_ZOOM_OUT to "ZOOMOUT",
    KeyEvent.KEYCODE_F1 to "F1",
    KeyEvent.KEYCODE_F2 to "F2",
    KeyEvent.KEYCODE_F3 to "F3",
    KeyEvent.KEYCODE_F4 to "F4",
    KeyEvent.KEYCODE_F5 to "F5",
    KeyEvent.KEYCODE_F6 to "F6",
    KeyEvent.KEYCODE_F7 to "F7",
    KeyEvent.KEYCODE_F8 to "F8",
    KeyEvent.KEYCODE_F9 to "F9",
    KeyEvent.KEYCODE_F10 to "F10",
    KeyEvent.KEYCODE_F11 to "F11",
    KeyEvent.KEYCODE_F12 to "F12",
    KeyEvent.KEYCODE_NUMPAD_0 to "KP0",
    KeyEvent.KEYCODE_NUMPAD_1 to "KP1",
    KeyEvent.KEYCODE_NUMPAD_2 to "KP2",
    KeyEvent.KEYCODE_NUMPAD_3 to "KP3",
    KeyEvent.KEYCODE_NUMPAD_4 to "KP4",
    KeyEvent.KEYCODE_NUMPAD_5 to "KP5",
    KeyEvent.KEYCODE_NUMPAD_6 to "KP6",
    KeyEvent.KEYCODE_NUMPAD_7 to "KP7",
    KeyEvent.KEYCODE_NUMPAD_8 to "KP8",
    KeyEvent.KEYCODE_NUMPAD_9 to "KP9",
    KeyEvent.KEYCODE_NUMPAD_DOT to "KP_DEC",
    KeyEvent.KEYCODE_NUMPAD_ENTER to "KP_ENTER",
    KeyEvent.KEYCODE_PROG_RED to "F13",
    KeyEvent.KEYCODE_PROG_GREEN to "F14",
    KeyEvent.KEYCODE_PROG_YELLOW to "F15",
    KeyEvent.KEYCODE_PROG_BLUE to "F16",
)
